function mergePosNegPair(pos_txt,neg_txt,is_shuffle,out_txt)
%input
%  pos_txt      --positive pair txt generated by makePosPair.m
%  neg_txt      --positive pair txt generated by makePosPair.m
%  is_shuffle   --randomly permute the positive pair
%output
%  out_txt      --merged pair txt
%
%Jun Hu
%2017-4
fid=fopen(pos_txt,'rt');
pos_list=textscan(fid,'%s %s %d');
fclose(fid);

fid=fopen(neg_txt,'rt');
neg_list=textscan(fid,'%s %s %d');
fclose(fid);
ori=[pos_list{1};neg_list{1}];
pair=[pos_list{2};neg_list{2}];
label=[pos_list{3};neg_list{3}];
if is_shuffle
    r=randperm(length(ori));
    ori=ori(r);
    pair=pair(r);
    label=label(r);
end

fid=fopen(out_txt,'wt');

for i=1:length(ori)
    fprintf(fid,'%s %s %d\n',ori{i},pair{i},label(i));
end

fclose(fid);
end
