function splitPair(pair_txt)
%to split pair(origin image, pair image,label) to (origin image,label) ...
%  and (pair image,label) for training network.
%input:
%  pair_txt     --pair txt generated by makePosPair.m or makeNegPair.m
%
%output:
%      two txt  --One is (origin image,label), another is (pair image,label)
%
%Jun Hu
%2017-4
fid=fopen(pair_txt,'rt');
list=textscan(fid,'%s %s %d');
fclose(fid);
ori=list{1};pair=list{2};label=list{3};
fid=fopen([pair_txt '-ori'],'wt');
for i=1:length(ori)
 fprintf(fid,'%s %d\n',ori{i},label(i));
end
fclose(fid);
fid=fopen([pair_txt '-pair'],'wt');
for i=1:length(ori)
 fprintf(fid,'%s %d\n',pair{i},label(i));
end
fclose(fid);
end